Tons of fixes for almost each part of the code
emastra/autotrader-scraper pull request #10
Opened 2022-01-23 21:07 UTC by zpelechova

2022-02-03 07:03 UTC, pocesar requested changes
thanks @zpelechova! some preliminary comments. 
when editing code, try not to change the formatting, it can be hard to keep track of changes. whitespace (new lines, indentation), `;`s and moving code up and down without changing it. 
make sure to always use `eslint` (and having the vscode extension installed) to spot some issues while coding. after that you can use the `npm run lint` command and it will show you the lines that are "out of style". some of those can be fixed with `npm run lint:fix`

2022-02-03 07:03 UTC, pocesar commented on INPUT_SCHEMA.json
> +            "description": "(Optional if 'predefined filters' are enabled) List of search URLs to start the scraping. It must be a search url including querystring for filters. Check documentation fo
make sure to test the INPUT_SCHEMA using `apify vis` command, before merging

2022-02-03 07:03 UTC, pocesar commented on INPUT_SCHEMA.json
> +            "default": false
is this a breaking change?

2022-02-03 07:03 UTC, pocesar commented on package.json
>  	"version": "0.0.1",
add the `devDependencies` here, so you can lint and fix errors before committing 
```suggestion
	"version": "0.0.1",
	"devDependencies": {
            "@apify/eslint-config": "^0.2.2",
            "eslint": "^8.7.0"
         },
```

the source files can be fixed using this script command:

```jsonc
    "scripts": {
        "start": "node src/main.js",
        "lint": "./node_modules/.bin/eslint ./src --ext .js,.jsx", 
        "lint:fix": "./node_modules/.bin/eslint ./src --ext .js,.jsx --fix",
        "test": "echo \"Error: oops, the actor has no tests yet, sad!\" && exit 1"
    },
```
run using `npm run lint:fix`

2022-02-03 07:03 UTC, pocesar commented on src/utils.js
> +    process.exit(1)
don't use `process.exit(1)` as it won't give enough time for the scraper to save stuff to the KV or RequestQueue

2022-02-03 07:03 UTC, pocesar commented on src/utils.js
> +    process.exit()
prefer using `crawler.autoscaledPool.abort()`

2022-02-09 14:23 UTC, zpelechova commented on INPUT_SCHEMA.json
> +            "description": "(Optional if 'predefined filters' are enabled) List of search URLs to start the scraping. It must be a search url including querystring for filters. Check documentation fo
Input schema is valid (response).

2022-02-09 14:24 UTC, zpelechova commented on INPUT_SCHEMA.json
> +            "default": false
Well, the actors hasnt worked at all for some time, so I dont think we have to worry about that. I changed it bcs of the logic of the input schema, would do the same if I only changed that...

2022-02-09 14:27 UTC, zpelechova commented on src/utils.js
> +    process.exit(1)
What else to use? Althought I dont think I added this there, I must have just changed the eslint on it.

2022-02-09 14:27 UTC, zpelechova commented on src/utils.js
> +    process.exit(1)
Oh I see, the think down!

2022-02-09 14:28 UTC, zpelechova commented on src/utils.js
> +    process.exit(1)
Right? crawler.autoscaledPool.abort() ?

2022-02-09 14:36 UTC, zpelechova commented on package.json
>  	"version": "0.0.1",
Cannot make it work: 
![image](https://user-images.githubusercontent.com/39551460/153223103-9c4b9139-79a0-4ffc-ad0b-b244a1a8383b.png)

2022-02-14 00:42 UTC, pocesar commented
@zpelechova added the lint and fixed the style issues

2022-02-18 12:31 UTC, metalwarrior665 reviewed
Just small comments

2022-02-18 12:31 UTC, metalwarrior665 commented on src/main.js
> +                        'Too many results for one scrape, splitting the search into two.',
Logs should always include info about the current URL and you could even add how you are gonna split it.

2022-02-18 12:31 UTC, metalwarrior665 commented on src/main.js
> +                    ],
No sure what formatting you use but the previous version is better I think

2022-02-18 12:31 UTC, metalwarrior665 commented
@zpelechova @pocesar We can merge?

2022-02-19 07:05 UTC, pocesar approved these changes

2022-02-21 09:15 UTC, merged